// Generated by CoffeeScript 1.6.3
(function() {
  var config, countrySchema, mongoose;

  mongoose = require('mongoose');

  config = require('../config');

  countrySchema = new mongoose.Schema({
    name: {
      type: String
    },
    dreams: {
      type: Number
    }
  });

  module.exports = mongoose.model('Country', countrySchema);

}).call(this);
