// Generated by CoffeeScript 1.6.3
(function() {
  var UserSchema, config, mongoose;

  mongoose = require('mongoose');

  config = require('../config');

  console.log(config);

  UserSchema = new mongoose.Schema({
    name: String,
    email: {
      type: String,
      lowercase: true
    },
    answers: {
      answerFuture: String,
      answerGoals: String
    },
    optionsSeen: [
      {
        answerGoals: String
      }
    ],
    location: String,
    demographics: {
      country: String,
      education: String,
      ethnicity: String,
      age: String,
      gender: String
    }
  });

  module.exports = mongoose.model('User', UserSchema);

}).call(this);
