// Generated by CoffeeScript 1.6.3
(function() {
  var config;

  config = {
    production: {
      google: {
        returnURL: 'http://realizechange.herokuapp.com/auth/google/callback',
        realm: 'http://realizechange.herokuapp.com/'
      },
      twitter: {},
      mongoUrl: 'mongodb://localhost/realizeChange',
      title: 'RealizeChange.org',
      subtitle: 'Making dreams come true...'
    },
    development: {
      google: {
        returnURL: 'http://localhost:1337/auth/google/callback',
        realm: 'http://localhost:1337/'
      },
      twitter: {},
      mongoUrl: 'mongodb://localhost/realizeChange',
      title: 'RealizeChange.org',
      subtitle: 'Making dreams come true...'
    }
  };

  module.exports = global.process.env.NODE_ENV === 'production' ? config.production : config.development;

}).call(this);
