// Generated by CoffeeScript 1.6.3
(function() {
  var config;

  config = {
    production: {
      google: {
        returnURL: 'http://realizechange.herokuapp.com/auth/google/callback',
        realm: 'http://realizechange.herokuapp.com/'
      },
      twitter: {},
      mongoUrl: 'mongodb://localhost/realize-change',
      title: 'Realize Change',
      subtitle: 'Let’s dream together...',
      info: {
        answers: "Please enter one dream and one goal that you have for the future. They do not have to be related.",
        seeanswers: 'Click on "All Dreams" to see all the dreams',
        rank: "Vote for the goal that you prefer. If you do not like either of them, vote for the lesser of two evils.",
        results: "These are the results from the Vote4Change section. Use the icons to sort the list based on vote totals",
        mission: "This is more information about our project"
      }
    },
    development: {
      google: {
        returnURL: 'http://localhost:1337/auth/google/callback',
        realm: 'http://localhost:1337/'
      },
      twitter: {},
      mongoUrl: 'mongodb://localhost/realize-change',
      title: 'Realize Change',
      subtitle: 'Let’s dream together...',
      info: {
        answers: "Please enter one dream and one goal that you have for the future. They do not have to be related.",
        seeanswers: 'Click on "All Dreams" to see all the dreams',
        rank: "Vote for the goal that you prefer. If you do not like either of them, vote for the lesser of two evils.",
        results: "These are the results from the Vote4Change section. Use the icons to sort the list based on vote totals",
        mission: "This is more information about our project"
      }
    }
  };

  module.exports = global.process.env.NODE_ENV === 'production' ? config.production : config.development;

}).call(this);
