// Generated by CoffeeScript 1.6.3
(function() {
  var links;

  links = [
    {
      label: 'Answer Questions',
      key: 'answers',
      path: '/answers'
    }, {
      label: 'See Answers',
      key: 'seeanswers',
      path: '/seeanswers'
    }, {
      label: 'Rank Answers',
      key: 'rank',
      path: '/rank'
    }, {
      label: 'See Results',
      key: 'results',
      path: '/results'
    }, {
      label: 'Mission/Donate',
      key: 'mission',
      path: '/mission'
    }
  ];

  module.exports = links;

}).call(this);
