// Generated by CoffeeScript 1.6.3
(function() {
  var links;

  links = [
    {
      label: ' Begin Dreaming',
      key: 'answers',
      path: '/answers',
      icon: 'fa-bell'
    }, {
      label: ' Dreams',
      key: 'seeanswers',
      path: '/seeanswers',
      icon: 'fa-globe'
    }, {
      label: ' Vote4Goals',
      key: 'rank',
      path: '/rank',
      icon: 'fa-thumbs-up'
    }, {
      label: ' Results',
      key: 'results',
      path: '/results',
      icon: 'fa-eye'
    }, {
      label: ' About Us and More',
      key: 'mission',
      path: '/mission',
      icon: 'fa-cloud'
    }
  ];

  module.exports = links;

}).call(this);
