// Generated by CoffeeScript 1.6.3
(function() {
  var links;

  links = [
    {
      label: 'Begin Dreaming',
      key: 'answers',
      path: '/answers',
      icon: 'fa-cloud'
    }, {
      label: 'Dreams',
      key: 'seeanswers',
      path: '/seeanswers',
      icon: 'fa-globe'
    }, {
      label: 'Vote4goals',
      key: 'rank',
      path: '/rank',
      icon: 'fa-thumbs-o-up'
    }, {
      label: 'Results',
      key: 'results',
      path: '/results',
      icon: 'fa-flag-checkered'
    }, {
      label: 'About Us',
      key: 'mission',
      path: '/mission',
      icon: 'fa-info-circle'
    }
  ];

  module.exports = links;

}).call(this);
