// Generated by CoffeeScript 1.6.3
(function() {
  var mongoose, user;

  mongoose = require('mongoose');

  user = require('./../models/user');

  exports.index = function(req, res) {
    if (req.user === void 0) {
      return res.render("index", {
        title: app.locals.config.title,
        subtitle: app.locals.config.subtitle
      });
    } else {
      return res.render("index", {
        title: app.locals.config.title,
        subtitle: app.locals.config.subtitle,
        username: req.user.name
      });
    }
  };

  exports.main = function(req, res) {
    return res.render('index', {
      title: app.locals.config.title,
      subtitle: app.locals.config.subtitle,
      username: req.user.name,
      200: 200
    });
  };

  exports.login = function(req, res) {
    return res.render('index', {
      title: app.locals.config.title,
      subtitle: app.locals.config.subtitle,
      username: "login",
      200: 200
    });
  };

  exports.answers = function(req, res) {
    var renderObj;
    req.session.redirectURL = req.url;
    renderObj = {};
    renderObj.title = app.locals.config.title;
    renderObj.subtitle = app.locals.config.subtitle;
    renderObj.info = "Please enter one dream and one goal that you have for the future. They do not have to be related.";
    if (req.user === void 0) {
      return user.find({
        ip: req.headers['x-forwarded-for'] || req.connection.remoteAddress
      }, function(err, data) {
        if (data.toString() !== '') {
          console.log("data", data.toString());
          renderObj.answerFuture = data[0].answers.answerFuture;
          renderObj.answerGoals = data[0].answers.answerGoals;
          return res.render("partials/answers", renderObj);
        } else {
          return res.render("partials/answers", renderObj);
        }
      });
    } else {
      return user.find({
        _id: req.user._id
      }, function(err, data) {
        console.log("data", data);
        console.log("req", req.user);
        renderObj.answerFuture = data[0].answers.answerFuture;
        renderObj.answerGoals = data[0].answers.answerGoals;
        renderObj.username = req.user.name;
        return res.render("partials/answers", renderObj);
      });
    }
  };

  exports.seeanswers = function(req, res) {
    var renderObj;
    req.session.redirectURL = req.url;
    renderObj = {};
    renderObj.title = app.locals.config.title;
    renderObj.subtitle = app.locals.config.subtitle;
    renderObj.info = 'Click on "All Dreams" to see all the dreams';
    if (req.user === void 0) {
      return res.render("partials/seeanswers", renderObj);
    } else {
      renderObj.username = req.user.name;
      return res.render("partials/seeanswers", renderObj);
    }
  };

  exports.rank = function(req, res) {
    var renderObj;
    req.session.redirectURL = req.url;
    console.log("hey");
    renderObj = {};
    renderObj.title = app.locals.config.title;
    renderObj.subtitle = app.locals.config.subtitle;
    renderObj.info = "Vote for the goal that you prefer. If you do not like either of them, vote for the lesser of two evils.";
    if (req.user === void 0) {
      return res.render("partials/rank", renderObj);
    } else {
      renderObj.username = req.user.name;
      return res.render("partials/rank", renderObj);
    }
  };

  exports.results = function(req, res) {
    var renderObj;
    req.session.redirectURL = req.url;
    console.log("hey");
    renderObj = {};
    renderObj.title = app.locals.config.title;
    renderObj.subtitle = app.locals.config.subtitle;
    renderObj.info = "These are the results from the Vote4Change section. Use the icons to sort the list based on vote totals";
    if (req.user === void 0) {
      return res.render("partials/results", renderObj);
    } else {
      renderObj.username = req.user.name;
      return res.render("partials/results", renderObj);
    }
  };

  exports.mission = function(req, res) {
    var renderObj;
    req.session.redirectURL = req.url;
    renderObj = {};
    renderObj.title = app.locals.config.title;
    renderObj.subtitle = app.locals.config.subtitle;
    renderObj.info = "This is more information about our project";
    console.log("reached mission");
    if (req.user === void 0) {
      return res.render("partials/mission", renderObj);
    } else {
      renderObj.username = req.user.name;
      return res.render("partials/mission", renderObj);
    }
  };

}).call(this);
