// Generated by CoffeeScript 1.6.3
(function() {
  exports.index = function(req, res) {
    return res.render('index', {
      title: app.locals.config.title,
      subtitle: app.locals.config.subtitle
    });
  };

  exports.main = function(req, res) {
    return res.render('index', {
      title: app.locals.config.title,
      subtitle: app.locals.config.subtitle,
      username: req.user.name,
      200: 200
    });
  };

  exports.login = function(req, res) {
    return res.render('index', {
      title: app.locals.config.title,
      subtitle: app.locals.config.subtitle,
      username: "login",
      200: 200
    });
  };

  exports.answers = function(req, res) {
    var renderObj;
    req.session.redirectURL = req.url;
    renderObj = {};
    renderObj.title = app.locals.config.title;
    renderObj.subtitle = app.locals.config.subtitle;
    renderObj.apikey = 'AIzaSyB_e3Hr9YXDi4P4JLX53yZOIr1Osz7L-_U';
    if (req.user === void 0) {
      return res.render("partials/answers", renderObj);
    } else {
      renderObj.username = req.user.name;
      return res.render("partials/answers", renderObj);
    }
  };

  exports.seeanswers = function(req, res) {
    var renderObj;
    req.session.redirectURL = req.url;
    renderObj = {};
    renderObj.title = app.locals.config.title;
    renderObj.subtitle = app.locals.config.subtitle;
    if (req.user === void 0) {
      return res.render("partials/seeanswers", renderObj);
    } else {
      renderObj.username = req.user.name;
      return res.render("partials/seeanswers", renderObj);
    }
  };

  exports.rank = function(req, res) {
    var renderObj;
    req.session.redirectURL = req.url;
    console.log("hey");
    renderObj = {};
    renderObj.title = app.locals.config.title;
    renderObj.subtitle = app.locals.config.subtitle;
    if (req.user === void 0) {
      return res.render("partials/rank", renderObj);
    } else {
      renderObj.username = req.user.name;
      return res.render("partials/rank", renderObj);
    }
  };

  exports.results = function(req, res) {
    var renderObj;
    req.session.redirectURL = req.url;
    console.log("hey");
    renderObj = {};
    renderObj.title = app.locals.config.title;
    renderObj.subtitle = app.locals.config.subtitle;
    if (req.user === void 0) {
      return res.render("partials/results", renderObj);
    } else {
      renderObj.username = req.user.name;
      return res.render("partials/results", renderObj);
    }
  };

  exports.mission = function(req, res) {
    req.session.redirectURL = req.url;
    console.log("reached mission");
    return res.render('partials/mission', {
      title: app.locals.config.title,
      subtitle: app.locals.config.subtitle
    });
  };

  exports.cancel = function(req, res) {
    return res.send("The payment got canceled");
  };

}).call(this);
