// Generated by CoffeeScript 1.6.3
(function() {
  var configPaypal, paypal;

  paypal = require('paypal-rest-sdk');

  configPaypal = {};

  exports.init = function(c) {
    configPaypal = c;
    return paypal.configure(c.api);
  };

}).call(this);
