// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = function(GlobalAnswer, app, user) {
    var answer_requests, getanswers, sendanswer;
    answer_requests = require('./answer_requests');
    sendanswer = app.get('/sendanswer', answer_requests)(GlobalAnswer, app, user).sendanswer;
    getanswers = app.get('/getanswers', answer_requests)(GlobalAnswer, app, user).getanswers;
    return {
      sendanswer: sendanswer,
      getanswers: getanswers
    };
  };

}).call(this);
