// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = function(GlobalAnswer, app) {
    return {
      sendanswer: require('./sendanswer')(GlobalAnswer, app).sendanswer,
      getanswers: require('./getanswers')(GlobalAnswer, app).getanswers
    };
  };

}).call(this);
