// Generated by CoffeeScript 1.6.3
(function() {
  var GlobalAnswer, mongoose, user;

  mongoose = require('mongoose');

  GlobalAnswer = require('./../Models/answers');

  user = require('./../Models/User');

  exports.newsettings = function(req, res) {
    return user.find({
      name: "" + req.user.name
    }, function(err, userToUpdate) {
      return userToUpdate[0].update({
        demographics: {
          country: req.query.country,
          ethnicity: req.query.ethnicity,
          age: req.query.age,
          gender: req.query.gender,
          education: req.query.education
        }
      }, function(err) {
        if (err) {
          throw err;
        }
        return res.send({
          success: "success"
        });
      });
    });
  };

}).call(this);
