// Generated by CoffeeScript 1.6.3
(function() {
  var GlobalAnswer, mongoose, user;

  mongoose = require('mongoose');

  GlobalAnswer = require('./../Models/answers');

  user = require('./../Models/User');

  exports.newsettings = function(req, res) {
    return console.log("req", req.query);
  };

}).call(this);
