// Generated by CoffeeScript 1.6.3
(function() {
  var GlobalAnswer, mongoose, user;

  mongoose = require('mongoose');

  GlobalAnswer = require('./../Models/answers');

  user = require('./../Models/User');

  exports.upvote = function(req, res) {
    console.log(req.query.currentId);
    return GlobalAnswer.findByIdAndUpdate(req.query.currentId, {
      $inc: {
        votes: 1
      }
    }, function(err, data) {
      console.log("data", data);
      if (err) {
        throw err;
      }
      return user.find({
        name: "" + req.user.name
      }, function(err, data) {
        if (data[0].optionsSeen) {
          console.log('array');
          return user.findOneAndUpdate({
            name: "" + req.user.name
          }, {
            $push: {
              optionsSeen: req.query.currentId
            }
          }, function(err, data) {
            if (err) {
              throw err;
            }
            return res.send({
              success: "success"
            });
          });
        } else {
          console.log('no array');
          return user.find({
            name: "" + req.user.name
          }, function(err, data) {
            data[0].save({
              optionsSeen: [req.query.currentId]
            });
            if (err) {
              throw err;
            }
            return res.send({
              success: "success"
            });
          });
        }
      });
    });
  };

}).call(this);
