// Generated by CoffeeScript 1.6.3
(function() {
  var GlobalAnswer, mongoose, user;

  mongoose = require('mongoose');

  GlobalAnswer = require('./../models/answers');

  user = require('./../models/user');

  exports.upvote = function(req, res) {
    console.log(req.query.otherId);
    return GlobalAnswer.findByIdAndUpdate(req.query.chosenId, {
      $inc: {
        votes: 1
      }
    }, function(err, data) {
      var chosenId, otherId, userName;
      console.log("data", data);
      if (err) {
        throw err;
      } else {
        userName = req.user.name;
        chosenId = req.query.chosenId;
        otherId = req.query.otherId;
        return user.find({
          name: userName
        }, function(err, userData) {
          if (err) {
            throw err;
          } else if (userData[0].optionsSeen) {
            return user.findOneAndUpdate({
              _id: "" + req.user._id
            }, {
              $pushAll: {
                optionsSeen: [chosenId, otherId],
                optionsChosen: [chosenId]
              }
            }, function(err, data) {
              if (err) {
                throw err;
              }
              console.log("data", data);
              return res.send({
                success: "success"
              });
            });
          } else {
            console.log('no array');
            return user.find({
              _id: "" + req.user._id
            }, function(data, err) {
              data[0].save({
                optionsSeen: [req.query.chosenId, req.query.otherId],
                optionsChosen: chosenId
              });
              if (err) {
                throw err;
              }
              return res.send({
                success: "success"
              });
            });
          }
        });
      }
    });
  };

}).call(this);
